#!/bin/sh
#
#= Evutils - Cache Library
#
# Library to handle dealing with caching for evutils programs.



# Cache Files
EVUTILS_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}/evutils"
# Error Logs.
EVUTILS_LOGS="$EVUTILS_CACHE_HOME/log"
# Cache of installed binaries in the system.
EVUTILS_PROGRAM_CACHE="$EVUTILS_CACHE_HOME/programs"
# Cache of evl's recently launched programs.
EVL_HISTFILE="$EVUTILS_CACHE_HOME/evl-history"
# Cache of eved's recently opened files.
EVED_HISTFILE="$EVUTILS_CACHE_HOME/eved-history"
# Cache of evop's recently opened files.
EVOP_HISTFILE="$EVUTILS_CACHE_HOME/evop-history"
# Cache of evbookarks's recently opened bookmarks.
EVBM_HISTFILE="$EVUTILS_CACHE_HOME/evbm-history"
# Cache of evemoji's recently used emojis.
EVEMOJI_HISTFILE="$EVUTILS_CACHE_HOME/evemoji-history"

# Create evutil's cache dir.
#
create_cache_dir() {
    mkdir -p "$EVUTILS_CACHE_HOME"
}

# Delete evutil's cache.
#
delete_cache() {
    rm -rf "$EVUTILS_CACHE_HOME" >/dev/null 2>&1
}

# Clear error logs
#
clear_logs() {
    if [ -f "$EVUTILS_LOGS" ]; then
        printf "" > "$EVUTILS_LOGS"
    fi
}

# Clear installed programs cache.
#
clear_program_cache() {
    if [ -f "$EVUTILS_PROGRAM_CACHE" ]; then
        printf "" > "$EVUTILS_PROGRAM_CACHE"
    fi
}

# Clear evl's cache.
#
clear_evl_hist() {
    if [ -f "$EVL_HISTFILE" ]; then
        printf "" > "$EVL_HISTFILE"
    fi
}

# Clear eved's cache.
#
clear_eved_hist() {
    if [ -f "$EVED_HISTFILE" ]; then
        printf "" > "$EVED_HISTFILE"
    fi
}

# Clear evop's cache.
#
clear_evop_hist() {
    if [ -f "$EVOP_HISTFILE" ]; then
        printf "" > "$EVOP_HISTFILE"
    fi
}

# Clear evbm's cache.
#
clear_evbm_hist() {
    if [ -f "$EVBM_HISTFILE" ]; then
        printf "" > "$EVBM_HISTFILE"
    fi
}

# Clear evemoji's cache.
#
clear_evemoji_hist() {
    if [ -f "$EVEMOJI_HISTFILE" ]; then
        printf "" > "$EVEMOJI_HISTFILE"
    fi
}

# Clear all evutils history.
#
clear_history() {
    clear_evl_hist
    clear_eved_hist
    clear_evop_hist
    clear_evbm_hist
    clear_evemoji_hist
}

# Clear all evutils programs cache.
#
clear_cache() {
    clear_logs
    clear_program_cache
    clear_evl_hist
    clear_eved_hist
    clear_evop_hist
    clear_evbm_hist
    clear_evemoji_hist
}

