#!/bin/sh
#
#= Evutils - Configuration Library
#
# Library to handle configuration file for evutils.



if [ "$EVUTILS_CONFIG_UPDATED" ]; then
    return
fi

EVUTILS_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/evutils"
EVUTILSRC="$EVUTILS_CONFIG_HOME/rc"
EVUTILS_DEFRC="$EVUTILS_HOME/examples/rc"
EVBROWSERRC="$EVUTILS_CONFIG_HOME/evbrowserrc"

# Configuration Variables
# The default terminal to use.
EVUTILS_TERM=${EVUTILS_TERM:-}
# The default terminal editor to use.
EVUTILS_TERM_EDITOR=${EVUTILS_TERM_EDITOR:-}
# The default terminal file manager to use.
EVUTILS_TERM_FM=${EVUTILS_TERM_FM:-}
# Additional options for GUI menu.
EVUTILS_GUI_MENU_OPTS=${EVUTILS_GUI_MENU_OPTS:-}
# Additional options for terminal menu.
EVUTILS_TERM_MENU_OPTS=${EVUTILS_TERM_MENU_OPTS:-}
# The default browser use.
EVUTILS_BROWSER=${EVUTILS_BROWSER:-}
# The default image viewer to use.
EVUTILS_IMAGE_VIEWER=${EVUTILS_IMAGE_VIEWER:-}
# The default audio player to use.
EVUTILS_AUDIO_PLAYER=${EVUTILS_AUDIO_PLAYER:-}
# The default video player to use.
EVUTILS_VIDEO_PLAYER=${EVUTILS_VIDEO_PLAYER:-}
# The default document reader to use.
EVUTILS_READER=${EVUTILS_READER:-}
# Path to bookmarks file to use.
EVUTILS_BOOKMARKS=${EVUTILS_BOOKMARKS:-}
# Path to screen layout setter script file.
EVUTILS_SCREENLAYOUTRC=${EVUTILS_SCREENLAYOUTRC:-}
# Path to screen layout presets file.
EVUTILS_SCREENLAYOUT_PRESETS=${EVUTILS_SCREENLAYOUT_PRESETS:-}
# Path to wallpaper setter script file.
EVUTILS_WALLPAPERRC=${EVUTILS_WALLPAPERRC:-}
# Path to wallpaper presets file.
EVUTILS_WALLPAPER_PRESETS=${EVUTILS_WALLPAPER_PRESETS:-}
# Directories to search for wallpapers. List separated by :.
EVUTILS_WALLPAPERS_PATH=${EVUTILS_WALLPAPERS_PATH:-}
# Enable/Disable notifications.
EVUTILS_NOTIFICATIONS=${EVUTILS_NOTIFICATIONS:-0}
# Enable/Disable logging errors.
EVUTILS_LOG=${EVUTILS_LOG:-0}
# Message verbosity level.
EVUTILS_VERBOSITY_LVL=${EVUTILS_VERBOSE:-3}

# Create evutils configuration directory if it doesn't exist
#
mk_config_dir() {
    mkdir -p "$EVUTILS_CONFIG_HOME"
}

# Make a running configuration file if it doesn't exist. 
#
mk_config_file() {
    mk_config_dir

    if ! [ -e "$EVUTILSRC" ]; then
        cp "$EVUTILS_DEFRC" "$EVUTILSRC"
    fi
}

# Update configuration variables from running configuration file.
#
update_config() {
    mk_config_file

    tmp=$(mktemp)

    awk '!/^ *#/ && NF' "$EVUTILSRC" > "$tmp"

    while IFS=$(printf '[ \t]*=[ \t]*') read name value; do
        unset IFS
        case $name in
            term)
                EVUTILS_TERM=${EVUTILS_TERM:-$(eval echo "$value")}
                ;;
            term_editor)
                EVUTILS_TERM_EDITOR=${EVUTILS_TERM_EDITOR:-$(eval echo "$value")}
                ;;
            term_fm)
                EVUTILS_TERM_FM=${EVUTILS_TERM_FM:-$(eval echo "$value")}
                ;;
            gui_menu_opts)
                EVUTILS_GUI_MENU_OPTS=${EVUTILS_GUI_MENU_OPTS:-$(eval echo "$value")}
                ;;
            term_menu_opts)
                EVUTILS_TERM_MENU_OPTS=${EVUTILS_TERM_MENU_OPTS:-$(eval echo "$value")}
                ;;
            browser)
                EVUTILS_BROWSER=${EVUTILS_BROWSER:-$(eval echo "$value")}
                ;;
            image_viewer)
                EVUTILS_IMAGE_VIEWER=${EVUTILS_IMAGE_VIEWER:-$(eval echo "$value")}
                ;;
            audio_player)
                EVUTILS_AUDIO_PLAYER=${EVUTILS_AUDIO_PLAYER:-$(eval echo "$value")}
                ;;
            video_player)
                EVUTILS_VIDEO_PLAYER=${EVUTILS_VIDEO_PLAYER:-$(eval echo "$value")}
                ;;
            reader)
                EVUTILS_READER=${EVUTILS_READER:-$(eval echo "$value")}
                ;;
            bookmarks)
                EVUTILS_BOOKMARKS=${EVUTILS_BOOKMARKS:-$(eval echo "$value")}
                ;;
            screenlayout_script)
                EVUTILS_SCREENLAYOUTRC=${EVUTILS_SCREENLAYOUTRC:-$(eval echo "$value")}
                ;;
            screenlayout_presets)
                EVUTILS_SCREENLAYOUT_PRESETS=${EVUTILS_SCREENLAYOUT_PRESETS:-$(eval echo "$value")}
                ;;
            wallpaper_script)
                EVUTILS_WALLPAPERRC=${EVUTILS_WALLPAPERRC:-$(eval echo "$value")}
                ;;
            wallpaper_presets)
                EVUTILS_WALLPAPER_PRESETS=${EVUTILS_WALLPAPER_PRESETS:-$(eval echo "$value")}
                ;;
            wallpaper_dirs)
                EVUTILS_WALLPAPERS_PATH=${EVUTILS_WALLPAPERS_PATH:-$(eval echo "$value")}
                ;;
            notifications)
                setting_val=$(eval echo "$value")
                case $setting_val in
                    true|1)
                        EVUTILS_NOTIFICATIONS=${EVUTILS_NOTIFICATIONS:-0}
                        ;;
                    false|0)
                        EVUTILS_NOTIFICATIONS=${EVUTILS_NOTIFICATIONS:-1}
                        ;;
                esac
                case $EVUTILS_NOTIFICATIONS in
                    0|1)
                        ;;
                    *)
                        EVUTILS_NOTIFICATIONS=0
                        ;;
                esac
                ;;
            log)
                setting_val=$(eval echo "$value")
                case $setting_val in
                    true|1)
                        EVUTILS_LOG=${EVUTILS_LOG:-0}
                        ;;
                    false|0)
                        EVUTILS_LOG=${EVUTILS_LOG:-1}
                        ;;
                esac
                case $EVUTILS_LOG in
                    0|1)
                        ;;
                    *)
                        EVUTILS_LOG=0
                        ;;
                esac
                ;;
            verbosity)
                setting_val=$(eval echo "$value")
                case $setting_val in
                    0|none)
                        EVUTILS_VERBOSITY_LVL=${EVUTILS_VERBOSITY_LVL:-0}
                        ;;
                    1|errors)
                        EVUTILS_VERBOSITY_LVL=${EVUTILS_VERBOSITY_LVL:-1}
                        ;;
                    2|warnings)
                        EVUTILS_VERBOSITY_LVL=${EVUTILS_VERBOSITY_LVL:-2}
                        ;;
                    3|status|all)
                        EVUTILS_VERBOSITY_LVL=${EVUTILS_VERBOSITY_LVL:-3}
                        ;;
                esac
                case $EVUTILS_VERBOSITY_LVL in
                    0|1|2|3)
                        ;;
                    *)
                        EVUTILS_VERBOSITY_LVL=3
                        ;;
                esac
                ;;
            *)
                echo ":: [WARNING] evutils Configuration: Unknown setting $name. Ignoring..." >&2
                ;;
        esac
    done < "$tmp"

    rm -f "$tmp"

    EVUTILS_CONFIG_UPDATED=0
}

update_config

