#!/bin/awk -f

!/\
\.git\/\
/\
&&
!/\
\.[Pp][Nn][Gg]$|\
\.[Jj][Pp][Gg]$|\
\.[Jj][Pp][Ee][Gg]$|\
\.[Pp][Gg][Mm]$|\
\.[Gg][Ii][Ff]$|\
\.[Pp][Pp][Mm]$|\
\.[Bb][Mm][Pp]$|\
\.[Pp][Bb][Mm]$|\
\.[Pp][Nn][Mm]$|\
\.[Ww][Ee][Bb][Pp]$|\
\.[Jj][Pp][Ee]$|\
\.[Jj][Ii][Ff]$|\
\.[Jj][Ff][Ii][Ff]$|\
\.[Jj][Ff][Ii]$|\
\.[Tt][Ii][Ff][Ff]$|\
\.[Tt][Ii][Ff]$|\
\.[Dd][Ii][Bb]$|\
\.[Hh][Ee][Ii][Ff]$|\
\.[Hh][Ee][Ii][Cc]$|\
\.[Jj][Pp]2$|\
\.[Jj][Pp][Ff]$|\
\.[Jj][Pp][Xx]$|\
\.[Jj][Pp][Mm]$|\
\.[Jj]2[Kk]$|\
\.[Mm][Jj]2$\
/\
&&
!/\
\.[Pp][Nn][Gg]$|\
\.[Jj][Pp][Gg]$|\
\.[Jj][Pp][Ee][Gg]$|\
\.[Pp][Gg][Mm]$|\
\.[Gg][Ii][Ff]$|\
\.[Pp][Pp][Mm]$|\
\.[Bb][Mm][Pp]$|\
\.[Pp][Bb][Mm]$|\
\.[Pp][Nn][Mm]$|\
\.[Ww][Ee][Bb][Pp]$|\
\.[Jj][Pp][Ee]$|\
\.[Jj][Ii][Ff]$|\
\.[Jj][Ff][Ii][Ff]$|\
\.[Jj][Ff][Ii]$|\
\.[Tt][Ii][Ff][Ff]$|\
\.[Tt][Ii][Ff]$|\
\.[Dd][Ii][Bb]$|\
\.[Hh][Ee][Ii][Ff]$|\
\.[Hh][Ee][Ii][Cc]$|\
\.[Jj][Pp]2$|\
\.[Jj][Pp][Ff]$|\
\.[Jj][Pp][Xx]$|\
\.[Jj][Pp][Mm]$|\
\.[Jj]2[Kk]$|\
\.[Mm][Jj]2$\
/\
&&\
!/\
\.[Pp][Dd][Ff]$|\
\.[Pp][Ss]$|\
\.[Dd][Jj][Vv][Uu]$|\
\.[Xx][Pp][Ss]$|\
\.[Cc][Bb][Zz]$|\
\.[Cc][Bb][Aa]$|\
\.[Cc][Bb][Rr]$|\
\.[Cc][Bb][Tt]$|\
\.[Cc][Bb]7$\
/\
&&
!/\
\.tar$|\
\.tar\.xz$|\
\.tar\.bz2$|\
\.tar\.gz$|\
\.tar\.zst$|\
\.bz2$|\
\.tbz2$|\
\.tgz$|\
\.rar$|\
\.gz$|\
\.zip$|\
\.Z$|\
\.7z$|\
\.deb$\
/
