#!/bin/sh
#
#= Evutils - Evaudio
#
# Audio output setter.
#
#
#== Synopsis
#
# evaudio



. "$EVUTILS_HOME/lib/log"
. "$EVUTILS_HOME/lib/audio"
. "$EVUTILS_HOME/lib/list"

_audio_output_description=""
_sink_id=""
_sink_port_id=""

# Set the audio output to use.
#
_set_audio_output() {
    audio_outputs=$(get_alt_outputs)
    if ! [ "$audio_outputs" ]; then
        log_status "No alternate audio outputs available. Exiting..."
        exit
    fi

    if ! { [ -t 0 ] || [ -p /dev/stdin ]; }; then
        evmenu_opts="${evmenu_opts} --gui"
    else
        evmenu_opts="${evmenu_opts} --term"
    fi

    output_selection=$(get_keys --delim " , " --list "$audio_outputs" | eval evmenu "$evmenu_opts" --prompt "'Set Audio Output'")
    if ! [ "$output_selection" ]; then
        exit
    fi
    _audio_output_description=$output_selection
    _sink_id=$(get_val --key "$output_selection" --idx 2 --delim " , " --list "$audio_outputs")
    _sink_port_id=$(get_val --key "$output_selection" --idx 3 --delim " , " --list "$audio_outputs")
}

# Set audio output.
#
_run() {
    { set_output "$_sink_id" "$_sink_port_id" && log_status "Audio output set to ${_audio_output_description}."; } ||
        log_error "Setting audio output to ${_audio_output_description} failed."
}

main() {
    _set_audio_output
    _run
}

main

