#!/bin/sh
#
#= Evutils - Evctl
#
# Evutils controller.
#
#
#== Synopsis
#
# evctl [options] --cmd command ...
# evctl [options] command ...
# evctl [options] -- command ...
#
#
#== Options
#
# -c command, --cmd command
#    The command to run.
#    Available commands:
#    clear-cache = Clears all cache created.
#    rm-cache = Deletes all cache created.
#    clear-history = Clears all history.
#    clear-log = Clears logs.
#    log = Show logs using less.
#    elog = Show logs using eved.
#    update-history = Updates the availability of evop's and eved's history
#    files.
#    set-browser = Set the browser to use for evutils', programs overwriting the
#    browser set in configuration file.



. "$EVUTILS_HOME/lib/log"
. "$EVUTILS_HOME/lib/list"
. "$EVUTILS_HOME/lib/browser"
. "$EVUTILS_HOME/lib/cache"
. "$EVUTILS_HOME/lib/config"

_CMD_LIST="\
clear-cache
rm-cache
clear-history
clear-log
log
elog
update-history
set-browser\
"

_cmds=""

# Updates the availability of history file files.
# @param {path} 1 History file path.
#
_update_history_files() {
    IFS=$CHAR_NL
    for _file in $(cat "$1" 2>/dev/null); do
        unset IFS
        if ! [ -e "$_file" ]; then
            list_rm --file "$1" -- "$_file"
            log_status "${_file} from ${1} removed."
        fi
    done
}

# Updates the availability of evop's and eved's history files.
#
_update_history() {
    _update_history_files "$EVOP_HISTFILE"
    _update_history_files "$EVED_HISTFILE"
}

# Set default browser to use overriding the browser set in configuration
# file, using evmenu.
#
_set_browser() {
    if ! [ "$(get_available_browsers)" ]; then
        log_error "No available browsers. Exiting..."
    fi
    selection=""
    if ! { [ -t 0 ] || [ -p /dev/stdin ]; }; then
        selection=$(get_available_browsers | evmenu --gui --prompt "Set Browser")
    else
        selection=$(get_available_browsers | evmenu --term --prompt "Set Browser")
    fi
    if ! [ "$selection" ]; then
        exit
    fi
    mk_config_dir
    echo "$selection" > "$EVBROWSERRC" && log_status "Browser set to ${selection}"
}

# Run the commands.
#
_run() {
    IFS=:
    for cmd in $_cmds; do
        unset IFS
        case $cmd in
            clear-cache)
                log_status "Clearing cache..."
                { clear_cache && log_status "Cache cleared."; } \
                    || log_error "Clearing cache failed."
                ;;
            rm-cache)
                log_status "Deleting cache..."
                { clear_cache && log_status "Cache deleted."; } \
                    || log_error "Deleting cache failed."
                ;;
            clear-history)
                log_status "Clearing history..."
                { clear_history && log_status "History cleared."; } \
                    || log_error "Clearing history failed."
                ;;
            clear-log)
                log_status "Clearing logs..."
                { clear_logs && log_status "Logs cleared."; } \
                    || log_error "Clearing logs failed."
                ;;
            log)
                if [ -e "$EVUTILS_LOGS" ]; then
                    less "$EVUTILS_LOGS"
                else
                    log_status "No logs."
                fi
                ;;
            elog)
                if [ -e "$EVUTILS_LOGS" ]; then
                    eved --no-cache -- "$EVUTILS_LOGS"
                else
                    log_status "No logs."
                fi
                ;;
            update-history)
                _update_history
                ;;
            set-browser)
                _set_browser
                ;;
        esac
    done
}

# Returns true if the command option is supported and false otherwise.
# @param {string} 1 The command option
# @returns {bool} True if the command option is supported and false otherwise.
#
is_available_cmd() {
    if echo "$_CMD_LIST" | grep -Fqx -e "$1"; then
        return 0
    else
        return 1
    fi
}

main() {
    while [ "$1" ]; do
        case $1 in
            -c|--cmd)
                if is_available_cmd "$2"; then
                    _cmds=$(list_cat "$_cmds" "$2" ":")
                else
                    log_warning "Unknown command ${2}. Ignoring..."
                fi
                shift
                ;;
            --)
                shift
                break
                ;;
            -?*)
                log_warning "Unknown option ${1}. Ignoring..."
                ;;
            *)
                if is_available_cmd "$1"; then
                    _cmds=$(list_cat "$_cmds" "$1" ":")
                else
                    log_warning "Unknown command ${1}. Ignoring..."
                fi
                ;;
        esac
        shift
    done

    while [ "$1" ]; do
        if is_available_cmd "$1"; then
            _cmds=$(list_cat "$_cmds" "$1" ":")
        else
            log_warning "Unknown command ${1}. Ignoring..."
        fi
        shift
    done

    if [ "$_cmds" ]; then
        _run
    else
        log_status "No commands to run. Exiting..."
    fi
}

main "$@"

