#!/bin/sh
#
#= Evutils - Evman
#
# Open man page.
#
#
#== Synopsis
#
# evman [options]
# evman [options] --man man-page
# evman [options] man-page
# evman [options] -- man-page
#
#
#== Options
#
# -m man-page, --man man-page
#    The man page to open. If unset, select from a list of available man pages
#    using evmenu.
# 
# -p prompt, --prompt prompt
#    Use a different prompt for evmenu. Default is "Open".
#
# -t, --new-term
#    Open man page in a new terminal using evterm. This option will be enabled
#    by default if not run from an interactive shell. This option is ignored
#    if not in a graphical environment.
#
# --gui-menu
#    Attempt to use the --gui option for evmenu. If not in a graphical environment,
#    terminal menu is used.
#
# --term-menu
#    Attempt to use the --term option for evmenu.



. "$EVUTILS_HOME/lib/log"
. "$EVUTILS_HOME/lib/program"
. "$EVUTILS_HOME/lib/list"

_man_page=""
_prompt="Open"
_open_new_term=1

_evmenu_opts=""

# Set the man page to open.
#
_set_man_page() {
    if [ "$_man_page" ]; then
        return
    fi

    if ! { [ -t 0 ] || [ -p /dev/stdin ]; }; then
        _evmenu_opts="${_evmenu_opts} --gui"
    elif ! echo "$_evmenu_opts" | grep -Fq -e "--gui"; then
        _evmenu_opts="${_evmenu_opts} --term"
    fi

    selection=$(get_man_pages | eval evmenu "$_evmenu_opts" --prompt "'$_prompt'")

    if ! [ "$selection" ]; then
        exit
    fi

    _man_page=$selection
}

# Open the man page.
#
_run() {
    if ! { [ -t 0 ] || [ -p /dev/stdin ]; }; then
        _open_new_term=0
    fi

    if [ "$DISPLAY" ] && [ "$_open_new_term" -eq 0 ]; then
        evterm -- "man '${_man_page}'"
    else
        man "$_man_page"
    fi
}

main() {
    while [ "$1" ]; do
        case $1 in
            -m|--man)
                if is_man_page "$2"; then
                    _man_page=$2
                else
                    log_warning "Invalid man page ${2}. Ignoring..."
                fi
                shift
                ;;
            -p|--prompt)
                _prompt=$2
                shift
                ;;
            -t|--new-term)
                _open_new_term=0
                ;;
            --gui-menu)
                _evmenu_opts="${_evmenu_opts} --gui"
                ;;
            --term-menu)
                _evmenu_opts="${_evmenu_opts} --term"
                ;;
            --)
                shift
                break
                ;;
            -?*)
                log_warning "Unknown option ${1}. Ignoring..."
                ;;
            *)
                if is_man_page "$1"; then
                    _man_page=$1
                else
                    log_warning "Invalid man page ${1}. Ignoring..."
                fi
                ;;
        esac
        shift
    done

    while [ "$1" ]; do
        if is_man_page "$1"; then
            _man_page=$1
        else
            log_warning "Invalid man page ${1}. Ignoring..."
        fi
        shift
    done

    _set_man_page
    _run
}

main "$@"

