#!/bin/sh
#
#= Evutils - Evpause
#
# Play / pause / stop media players. If multiple players are running then evmenu
# is used to select which player to control.
#
#
#== Synopsis
#
# evpause [options]
#
#
#== Options
#
# -s, --stop
#    Stop the player instead of pausing or playing.

   

. "$EVUTILS_HOME/lib/log"
. "$EVUTILS_HOME/lib/std"
. "$EVUTILS_HOME/lib/media"
. "$EVUTILS_HOME/lib/list"

_PLAY_ALL_OPT=" Play All"
_PAUSE_ALL_OPT=" Pause All"
_STOP_ALL_OPT=" Stop All"

_stop=1

_player=""

# Set the player to control.
#
_set_player() {
    players=$(get_running_players)

    if ! [ "$players" ]; then
        log_status "No running players. Exiting..."
        exit
    elif [ "$(list_len --list "$players")" -eq 1 ]; then
        _player=$players
        return
    fi

    new_players=""
    IFS=$CHAR_NL
    for player in $players; do
        unset IFS
        metadata_title=$(playerctl --player="$player" metadata --format "{{title}}")
        new_players=$(list_cat "$new_players" "${player}${metadata_title:+ -- $metadata_title}")
    done

    prompt=""
    if [ "$_stop" -eq 0 ]; then
        new_players=$(list_cat "$new_players" "$_STOP_ALL_OPT")
        prompt=""
    else
        new_players=$(list_cat "$new_players" "$_PLAY_ALL_OPT")
        new_players=$(list_cat "$new_players" "$_PAUSE_ALL_OPT")
        prompt=" "
    fi

    selection=""
    if ! { [ -t 0 ] || [ -p /dev/stdin ]; }; then
        selection=$(echo "$new_players" | evmenu --gui --prompt "$prompt")
    else
        selection=$(echo "$new_players" | evmenu --term --prompt "$prompt")
    fi
    if ! [ "$selection" ]; then
        exit
    fi
    _player=${selection%% -- *}
}

# Control the player.
#
_run() {
    if [ "$_stop" -eq 0 ]; then
        case $_player in
            "$_STOP_ALL_OPT")
                player_stop
                ;;
            *)
                player_stop "$_player"
        esac
    else
        case $_player in
            "$_PLAY_ALL_OPT")
                player_play
                ;;
            "$_PAUSE_ALL_OPT")
                player_pause
                ;;
            *)
                player_toggle "$_player"
                ;;
        esac
    fi
}

main() {
    while [ "$1" ]; do
        case $1 in
            -s|--stop)
                _stop=0
                ;;
            -?*)
                log_warning "Unknown option ${1}. Ignoring..."
                ;;
        esac
        shift
    done

    _set_player
    _run
}

main "$@"

