#!/bin/sh
#
#= Evutils - Evspeedtest
#
# Run speedtest and display results in a notification.
#
#
#== Synopsis
#
# evspeedtest



. "$EVUTILS_HOME/lib/log"
. "$EVUTILS_HOME/lib/program"
. "$EVUTILS_HOME/lib/list"

# Check to see if speedtest is installed.
#
_pre() {
    if is_not_installed "speedtest"; then
        log_error "speedtest is not installed. Exiting..."
        exit 1
    fi
}

# Run speedtest.
#
_run() {
    log_status "Running speedtest..."
    speedtest_result=$(speedtest --csv --secure 2>/dev/null)
    if ! [ "$speedtest_result" ]; then
        log_error "No Internet Connection. Exiting..."
        exit 1
    fi
    ping=$(get_col --idx 6 --delim "," --list "$speedtest_result")
    download_speed=$(get_col --idx 7 --delim "," --list "$speedtest_result")
    upload_speed=$(get_col --idx 8 --delim "," --list "$speedtest_result")
    log_status "${ping} ms  ${download_speed} Mbit/s  ${upload_speed} Mbit/s"
}

main() {
    _pre
    _run
}

main

